# Site settings
name: Alexander Spanos
email: alexisspa9@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Ruby, Python, React, Startups, Agile, Pair Programming"
skills: "Senior Software Engineer in Paros, Greece"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/alexisspa9/
  - title: github
    url: https://github.com/alexisspa9/
  - title: twitter
    url: https://twitter.com/
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
